name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Your build steps here...

      # Modify commit message to include tag information
      - name: Add tag info to commit message
        run: |
          echo "Deploying tag: ${{ github.ref }}" >> commit_message.txt
          cat commit_message.txt # For verification, you can remove this line later
          git add commit_message.txt
          git commit -m "Add tag info to commit message"
          git push
