name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Your build steps here...

      # Modify commit message to include tag information
      - name: Add tag info to commit message
        run: echo "Deploying tag: ${{ github.ref }}" >> $GITHUB_EVENT_PATH

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Add tag info to commit message" || true
          git push
