name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        type: choice
        required: true
        default: 'STAGING'
        options:
          - QA
          - STAGING
          - UAT
          - SEA
          - CA
          - AU
          - EU
          - US
          - SG
          - GCC
          - WWW

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download tag name artifact
        uses: actions/download-artifact@v2
        with:
          name: tag-name
          path: tag

      - name: Read tag name from artifact
        id: read_tag
        run: |
          TAG_NAME=$(cat tag/tag-name)
          echo "::set-output name=tag_name::$TAG_NAME"

      - name: Deploy code
        run: |
          # Use ${{ github.event.inputs.tag_name }} wherever you need the tag name
          # If tag_name input is provided, use that, otherwise use the one from the artifact
          if [ -n "${{ github.event.inputs.tag_name }}" ]; then
            echo "Deploying tag ${{ github.event.inputs.tag_name }}"
          else
            echo "Deploying tag ${{ steps.read_tag.outputs.tag_name }}"
          fi
