name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        type: choice
        required: true
        default: 'STAGING'
        options:
          - QA
          - STAGING
          - UAT
          - SEA
          - CA
          - AU
          - EU
          - US
          - SG
          - GCC
          - WWW

      tag:
        description: 'Enter Tag'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: '0'

      - name: Get Tags and Check Tag Existence
        id: get_tags
        run: |
          TAGS=$(git ls-remote --tags origin | awk -F"/" '{print $3}')
          TAG_LIST=$(echo "${TAGS}" | tr '\n' ',')
          echo "tags=${TAG_LIST}"
          if echo "${TAGS}" | grep -q "\<${{ github.event.inputs.tag }}"; then
            echo "Tag ${{github.event.inputs.tag}} exists."
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Error: Tag does not exist."
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Sync S3
        if: env.TAG_EXISTS == 'true'
        run: |
          echo "S3 Sync Success"
      - name: Deploy if Tag Exists
        if: env.TAG_EXISTS == 'true'
        run: |
          echo "Deploying with tag: ${{ github.event.inputs.tag }} on ${{github.event.inputs.environment}}"
