name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        type: choice
        required: true
        default: 'STAGING'
        options:
          - QA
          - STAGING
          - UAT
          - SEA
          - CA
          - AU
          - EU
          - US
          - SG
          - GCC
          - WWW

      tag:
        description: 'Enter Tag'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Debugging Information
        run: |
          pwd
          ls -la
          git remote -v

      - name: Get Tags
        id: get_tags
        run: |
          TAGS=$(git ls-remote --tags origin | awk -F"/" '{print $3}')
          TAG_LIST=$(echo "${TAGS}" | tr '\n' ',')
          echo "Available tags: ${TAG_LIST}"
        
      - name: Check Tag Existence
        id: check_tag
        run: |
          if grep -q "\<${{ github.event.inputs.tag }}\>", <<<"${{ steps.get_tags.outputs.stdout }}"; then
            echo "Tag exists."
            echo "::set-output name=tag_exists::true"
          else
            echo "Error: Tag does not exist."
            echo "::set-output name=tag_exists::false"
            exit 1
          fi

      - name: Deploy if Tag Exists
        if: steps.check_tag.outputs.tag_exists == 'true'
        run: |
          # Your deployment commands using the provided tag
          echo "Deploying with tag: ${{ github.event.inputs.tag }}"
